### ISSUE TITLE
Allow Changing Month Text Color

### ISSUE THREAD

**Issue by aashutoshrathi** [grubersjoe/react-github-calendar#23]
Currently, the theme of the chart is configurable but the text color is fixed to be black.
Allow taking an option for textColor

**Comment by Clumsynite** [comment]
```css
svg.react-github-calendar__calendar text {
  fill: var(--main-fg) !important;
}
```
you can use this for now
